// Package config resolves aigit's runtime configuration from multiple sources.
//
// Settings are applied in priority order (highest to lowest):
//
//  1. CLI flags (--provider, --model, --url)
//  2. Environment variables (AIGIT_PROVIDER, AIGIT_MODEL, AIGIT_URL, AIGIT_PROMPT)
//  3. Config file (~/.config/aigit/config.json, or a custom path)
//  4. Built-in defaults (provider: auto, model: auto)
package config

import (
	"encoding/json"
	"os"
	"path/filepath"
)

// Default values used when no override is provided.
const (
	DefaultProvider = "auto"
	DefaultModel    = "auto"
	DefaultURL      = ""
)

// DefaultPrompt is the system prompt sent to the selected provider before the
// git diff.
// It instructs the model to produce a clean, conventional commit message
// with no extra commentary, markdown, or trailers.
const DefaultPrompt = `You are an expert software engineer writing git commit messages.

You will receive:
- A staged review summary generated by the tool
- The raw git diff

Use the staged review as supporting context, but treat the raw diff as the
source of truth.

Given a git diff, write a commit message following these rules:

Subject line (first line):
- Imperative mood, 72 characters or fewer, no trailing period
- Summarise the overall intent of the change, not the mechanism
- Do NOT mention file names unless the file itself is the entire point
- Do NOT start with "This commit", "This change", "I", or similar phrases

Body (after a blank line separating it from the subject):
- Always include a body unless the diff is trivially small (e.g. a typo fix)
- Wrap lines at 72 characters
- Explain WHY the change was made and any important context or trade-offs
- For changes that touch multiple areas, use a short bullet list (- item) to
  describe each logical area of change — one bullet per concern, not per file
- Use file-level details from the staged review only when they clarify the
  overall intent or important supporting changes
- Do NOT turn the commit message into a file-by-file changelog
- Be as detailed as the diff warrants; do not truncate or summarise away
  important context just to keep the message short

Formatting rules:
- Do NOT add a sign-off, Co-authored-by, or any trailer lines
- Do NOT wrap your output in markdown code fences
- Do NOT add any explanation or preamble outside the commit message itself
- Do NOT output reasoning traces, thinking tags, or hidden scratch work
- Output ONLY the raw commit message text, nothing else

Input to summarize:`

// Overrides carries values explicitly set via CLI flags.
// An empty string means "not set" — the next priority level will be used.
type Overrides struct {
	Provider string
	Model    string
	URL      string
}

// Config is the fully resolved configuration ready for use by the CLI.
type Config struct {
	Provider string // provider name: auto, ollama, or lmstudio
	Model    string // model name (or "auto" to resolve from the selected provider)
	URL      string // optional base URL override
	Prompt   string // System prompt prepended to the git diff
}

// Load builds a Config by merging defaults, config file, environment variables,
// and CLI flag overrides — in that order (later sources win).
//
// cfgPath is the path to a JSON config file. Pass an empty string to use the
// default location (~/.config/aigit/config.json). A missing file is silently
// ignored; a malformed file returns an error.
func Load(overrides Overrides, cfgPath string) (Config, error) {
	cfg := defaultConfig()

	resolvedPath := resolveConfigPath(cfgPath)
	if err := applyFileConfig(resolvedPath, &cfg); err != nil {
		return Config{}, err
	}

	applyEnvVars(&cfg)
	applyOverrides(overrides, &cfg)

	return cfg, nil
}

// defaultConfig returns a Config populated with built-in defaults.
func defaultConfig() Config {
	return Config{
		Provider: DefaultProvider,
		Model:    DefaultModel,
		URL:      DefaultURL,
		Prompt:   DefaultPrompt,
	}
}

// resolveConfigPath returns cfgPath if non-empty, otherwise the standard
// XDG-style path: ~/.config/aigit/config.json.
func resolveConfigPath(cfgPath string) string {
	if cfgPath != "" {
		return cfgPath
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".config", "aigit", "config.json")
}

// applyFileConfig reads a JSON config file and merges non-empty values into cfg.
// A missing file is silently ignored (not an error).
func applyFileConfig(path string, cfg *Config) error {
	if path == "" {
		return nil
	}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}

	var fc fileConfig
	if err := json.Unmarshal(data, &fc); err != nil {
		return err
	}
	fc.applyTo(cfg)
	return nil
}

// applyEnvVars merges AIGIT_* environment variables into cfg, overwriting any
// value set by the config file.
func applyEnvVars(cfg *Config) {
	if v := os.Getenv("AIGIT_PROVIDER"); v != "" {
		cfg.Provider = v
	}
	if v := os.Getenv("AIGIT_MODEL"); v != "" {
		cfg.Model = v
	}
	if v := os.Getenv("AIGIT_URL"); v != "" {
		cfg.URL = v
	}
	if v := os.Getenv("AIGIT_PROMPT"); v != "" {
		cfg.Prompt = v
	}
}

// applyOverrides merges CLI flag values into cfg, giving them the highest
// priority. Only non-empty override values take effect.
func applyOverrides(o Overrides, cfg *Config) {
	if o.Provider != "" {
		cfg.Provider = o.Provider
	}
	if o.Model != "" {
		cfg.Model = o.Model
	}
	if o.URL != "" {
		cfg.URL = o.URL
	}
}

// fileConfig mirrors the JSON structure of ~/.config/aigit/config.json.
type fileConfig struct {
	Provider string `json:"provider"`
	Model    string `json:"model"`
	URL      string `json:"url"`
	Prompt   string `json:"prompt"`
}

// applyTo copies non-empty fileConfig fields into cfg.
func (fc fileConfig) applyTo(cfg *Config) {
	if fc.Provider != "" {
		cfg.Provider = fc.Provider
	}
	if fc.Model != "" {
		cfg.Model = fc.Model
	}
	if fc.URL != "" {
		cfg.URL = fc.URL
	}
	if fc.Prompt != "" {
		cfg.Prompt = fc.Prompt
	}
}
